# This is a basic workflow to help you get started with Actions

name: 🚀 Deploy website on push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  web-deploy1:
    name: 🎉 Main Deploy
    runs-on: ubuntu-latest
    environment: default
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: goingpink.atwebpages.com
        ftp_username: ${{ secrets.FTP_USERNAME2 }}
        ftp_password: ${{ secrets.FTP_PASSWORD2 }}
        local_source_dir: "./"
        dist_target_dir: "/htdocs"
        delete: "false"
        only_newer: "true"
        exclude: "'^.github/'"

  web-deploy2:
    name: 🎉 Backup Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code (again)
        uses: actions/checkout@v2
      # Here is the deployment action
      - name: Upload from whatever dir via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: files.000webhost.com
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./"
          delete: "false"
          max_retries: "25"
          ftp_nop_interval: "10"
  
